### ISSUE TITLE
document screenshot is not same with description

### ISSUE THREAD

**Issue by himself65** [pingcap/pingcap.github.io#100]
https://github.com/pingcap/ossinsight-lite/blob/main/docs/setup/repo-and-action.md

![image](https://github.com/pingcap/ossinsight-lite/assets/14026360/5d23eaf0-e5e5-4421-8931-c56343596118)

**Comment by 634750802** [comment]
pipelines should automatically handle `mysql://` scheme (mysql2 also works.) see https://github.com/pingcap/ossinsight-lite/issues/71
