### ISSUE TITLE
Failed to build when deploy to Vercel

### ISSUE THREAD

**Issue by RenlySir** [pingcap/pingcap.github.io#116]
i get error as:
 when i delpoy in https://vercel.com/

ELIFECYCLE  Command failed with exit code 22.
--
18:49:26.951 | WARN   Local package.json exists, but node_modules missing, did you mean to install?
18:49:26.980 | Error: Command "pnpm run next:install" exited with 1
18:49:27.505 | BUILD_UTILS_SPAWN_1: Command "pnpm run next:install" exited with 1

**Comment by 634750802** [comment]
I have changed CI today. The document was outdated. See [prebuild.sh](https://github.com/pingcap/ossinsight-lite/blob/main/prebuild.sh)
