### ISSUE TITLE
tidb-plane 登录后布局有问题

### ISSUE THREAD

**Issue by ericsyh** [pingcap/pingcap.github.io#221]
### 问题描述
在https://pingcap.com/tidb-planet/user/ 上登录输入 github id 后，显示的布局有问题。头像过大而且所有信息都挤在左边
![image](https://user-images.githubusercontent.com/10498732/56633586-57275f80-6691-11e9-8ef1-150e4d4327c2.png)

### 复现步骤
1. 登录https://pingcap.com/tidb-planet/user/ 
2. 输入 github id
3. 跳转后，看到头像和相关信息都挤在左边，而且头像过大遮挡了信息。

### 期望
优化登录后布局

**Comment by YiniXu9506** [comment]
@ericsyh 非常感谢你的反馈，正在修复中。

**Comment by ericsyh** [comment]
hotfix PR merged @ https://github.com/pingcap/pingcap.github.io/pull/222
Close the issue.
