### ISSUE TITLE
Update TiDB Academy Landing Page

### ISSUE THREAD

**Issue by morgo** [pingcap/pingcap.github.io#55]
[This page](https://pingcap.com/tidb-academy/) can benefit from content:

# Distributed Database with TiDB for MySQL DBAs

## Who this course is designed for
This is an accelerated introduction course on TiDB targeted for those with a strong MySQL background.  In many cases we will explain TiDB concepts by using a direct comparison to MySQL.

## Format
This course uses a combination of videos and hands-on exercises.  Students may study at their own pace, with an instructor available to reach out to at any point.  Completion typically takes 20-30 hours.

## What you will learn
Students who successfully complete this course will be able to deploy TiDB in a production environment and perform common DBA tasks, such as backup & recovery, capacity planning and monitoring.

## Prerequisites
* This course assumes students have 3-5+ years experience using MySQL in a DBA or Architect role.
* Students should be comfortable typing commands in a bash shell and MySQL command line client.
* Previous exposure to Cloud technologies (i.e. Kubernetes) is beneficial but not required.

## Tuition Fees
This course is available free of charge!

**Comment by YiniXu9506** [comment]
Done
