### ISSUE TITLE
npm start error-怎么解决？

### ISSUE THREAD

**Issue by SoftwareKing** [pingcap/pingcap.github.io#80]
![image](https://user-images.githubusercontent.com/6858857/49324245-10f82500-f565-11e8-9198-8f66731f8e90.png)

**Comment by SoftwareKing** [comment]
@gregwebs

**Comment by YiniXu9506** [comment]
@SoftwareKing 请问你的 nodejs 版本是多少呢

**Comment by SoftwareKing** [comment]
```
xujindeMacBook-Pro:~ xujin$ node -v
v10.9.0
xujindeMacBook-Pro:~ xujin$，
```
我是直接把src分支下载下来，因为不可以clone。然后npm install，npm start报错。
@YiniXu9506 方便留个微信，或者加我微信Software_King，交流一下

**Comment by YiniXu9506** [comment]
@SoftwareKing 你的 nodejs 版本有点高。这个官网项目现在支持的是 v8.11.3

**Comment by SoftwareKing** [comment]
ok,我试试v8.11.3

**Comment by YiniXu9506** [comment]
Hi 同学，

你好，感谢你对 pingcap 的关注，不过我有点好奇你为什么对 pingcap 官网的 repo 感兴趣呢～

**Comment by SoftwareKing** [comment]
pingcap的站点构建方式比较独特，hugo，hexo我都用过，最近搞开源项目，调研一下。
